version: "3.7"
services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=test
    expose:
      - 3306
  mybb:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"
